terminate called after throwing an instance of 'leatherman::json_container::data_key_error'
  what():  unknown object entry with key: executable
